export const listData = [
    {
      id: 1,
      title: "A Great Apartment Next to the Beach!",
      images: ["/apartment 1.jpeg"],
      bedroom: 2,
      bathroom: 1,
      price: 1000,
      address: "456 Park Avenue, London",
      latitude: 51.5074,
      longitude: -0.1278,
    },
    {
      id: 2,
      title: "An Awesome Apartment Near the Park! Almost too good to be true!",
      images: ["/apartment 2.jpeg"],
      bedroom: 3,
      bathroom: 2,
      price: 1500,
      address: "789 Oxford Street, London",
      latitude: 52.4862,
      longitude: -1.8904,
    },
    {
      id: 3,
      title: "A New Apartment in the City!",
      images: ["/apartment 3.jpeg"],
      bedroom: 1,
      bathroom: 1,
      price: 800,
      address: "101 Baker Street, London",
      latitude: 53.4808,
      longitude: -2.2426,
    },
    {
      id: 4,
      title: "Great Location! Great Price! Great Apartment!",
      images: ["/apartment 4.jpeg"],
      bedroom: 2,
      bathroom: 1,
      price: 1000,
      address: "234 Kingsway, London,",
      latitude: 53.8008,
      longitude: -1.5491,
    },
    {
      id: 5,
      title: "Apartment 5",
      images: ["/apartment 5.jpeg"],
      bedroom: 3,
      bathroom: 2,
      price: 1500,
      address: "567 Victoria Road, London",
      latitude: 53.4084,
      longitude: -2.9916,
    },
    {
      id: 6,
      title: "Apartment 6",
      images: ["/apartment 6.jpeg"],
      bedroom: 1,
      bathroom: 1,
      price: 800,
      address: "890 Regent Street, London",
      latitude: 54.9783,
      longitude: -1.6174,
    },
    {
      id: 7,
      title: "Apartment 7",
      images: ["/apartment 7.jpeg"],
      bedroom: 2,
      bathroom: 1,
      price: 1000,
      address: "112 Piccadilly, London",
      latitude: 53.3811,
      longitude: -1.4701,
    },
    {
      id: 8,
      title: "Apartment 8",
      images: ["/apartment 8.jpeg"],
      bedroom: 3,
      bathroom: 2,
      price: 1500,
      address: "8765 Main High Street, London",
      latitude: 51.4545,
      longitude: -2.5879,
    },
  ];
  
  export const singlePostData = {
    id: 1,
    title: "Beautiful Apartment",
    price: 1200,
    images: [
      "/apartment 1.jpeg",
      "/apartment 2.jpeg",
      "/apartment 3.jpeg",
      "/apartment 4.jpeg",
    ],
    bedRooms: 2,
    bathroom: 1,
    size: 861,
    latitude: 51.5074,
    longitude: -0.1278,
    city: "London",
    address: "1234 Broadway St",
    school: "250m away",
    bus: "100m away",
    restaurant: "50m away",
    description:
      "Future alike hill pull picture swim magic chain seed engineer nest outer raise bound easy poetry gain loud weigh me recognize farmer bare danger. actually put square leg vessels earth engine matter key cup indeed body film century shut place environment were stage vertical roof bottom lady function breeze darkness beside tin view local breathe carbon swam declared magnet escape has from pile apart route coffee storm someone hold space use ahead sheep jungle closely natural attached part top grain your grade trade corn salmon trouble new bend most teacher range anybody every seat fifteen eventually",
  };
  
  export const userData = {
    id: 1,
    name: "John Doe",
    img: "/profile-img.jpeg",
  };