import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding Rwanda properties...");
  const pw = await bcrypt.hash("password123", 10);

  const a1 = await prisma.user.upsert({ where:{username:"agent_norah"}, update:{role:"agent"}, create:{username:"agent_norah",email:"norah@realestate.rw",password:pw,avatar:"https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=400",role:"agent"} });
  const a2 = await prisma.user.upsert({ where:{username:"agent_eric"}, update:{role:"agent"}, create:{username:"agent_eric",email:"eric@realestate.rw",password:pw,avatar:"https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=400",role:"agent"} });
  const a3 = await prisma.user.upsert({ where:{username:"agent_alice"}, update:{role:"agent"}, create:{username:"agent_alice",email:"alice@realestate.rw",password:pw,avatar:"https://images.pexels.com/photos/1181682/pexels-photo-1181682.jpeg?auto=compress&cs=tinysrgb&w=400",role:"agent"} });
  const a4 = await prisma.user.upsert({ where:{username:"agent_jean"}, update:{role:"agent"}, create:{username:"agent_jean",email:"jean@realestate.rw",password:pw,avatar:"https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=400",role:"agent"} });

  const posts = [
    // ── KIGALI ──────────────────────────────────────────────────────────
    { title:"Luxury Villa in Nyarutarama", price:2500, images:["https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=1260","https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=1260","https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=1260"], address:"KG 9 Ave, Nyarutarama, Kigali", city:"Kigali", bedroom:5, bathroom:4, latitude:-1.9365, longitude:30.0915, type:"rent", property:"house", agentIdx:1, desc:"Stunning 5-bedroom villa with swimming pool and beautiful garden in the most prestigious neighbourhood of Kigali. 24/7 security and backup power.", utilities:"tenant", pet:"allowed", income:"Proof of income required", size:450, school:500, bus:200, restaurant:300 },
    { title:"Modern Apartment in Kiyovu", price:1200, images:["https://images.pexels.com/photos/1571468/pexels-photo-1571468.jpeg?auto=compress&cs=tinysrgb&w=1260","https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=1260"], address:"KN 3 Rd, Kiyovu, Kigali", city:"Kigali", bedroom:2, bathroom:2, latitude:-1.9536, longitude:30.0605, type:"rent", property:"apartment", agentIdx:0, desc:"Executive 2-bedroom apartment with modern finishes and high-speed internet. Walking distance to the city centre and major banks.", utilities:"owner", pet:"not-allowed", income:"3x monthly rent", size:110, school:400, bus:100, restaurant:50 },
    { title:"Family Home in Rebero", price:350000, images:["https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1260","https://images.pexels.com/photos/1029599/pexels-photo-1029599.jpeg?auto=compress&cs=tinysrgb&w=1260"], address:"Rebero Hill, Kicukiro, Kigali", city:"Kigali", bedroom:4, bathroom:3, latitude:-1.9845, longitude:30.0712, type:"buy", property:"house", agentIdx:1, desc:"Spacious family home with breathtaking view of Kigali city. Quiet, secure neighbourhood with easy access to Kicukiro centre.", utilities:"tenant", pet:"allowed", income:"Mortgage pre-approval required", size:300, school:1200, bus:500, restaurant:800 },
    { title:"Studio Apartment in Kimihurura", price:600, images:["https://images.pexels.com/photos/2029694/pexels-photo-2029694.jpeg?auto=compress&cs=tinysrgb&w=1260","https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?auto=compress&cs=tinysrgb&w=1260"], address:"KG 11 Ave, Kimihurura, Kigali", city:"Kigali", bedroom:1, bathroom:1, latitude:-1.9432, longitude:30.0820, type:"rent", property:"apartment", agentIdx:2, desc:"Cosy studio apartment in the heart of Kimihurura, close to embassies and international schools. Fully furnished option available.", utilities:"owner", pet:"not-allowed", income:"2x monthly rent", size:55, school:300, bus:150, restaurant:100 },
    { title:"Commercial Plot in Gisozi", price:180000, images:["https://images.pexels.com/photos/440731/pexels-photo-440731.jpeg?auto=compress&cs=tinysrgb&w=1260","https://images.pexels.com/photos/280229/pexels-photo-280229.jpeg?auto=compress&cs=tinysrgb&w=1260"], address:"Gisozi, Gasabo, Kigali", city:"Kigali", bedroom:0, bathroom:0, latitude:-1.9150, longitude:30.0700, type:"buy", property:"land", agentIdx:3, desc:"Prime commercial plot of 1000 sqm in fast-developing Gisozi area. Ideal for office block, hotel or mixed-use development. Title deed available.", utilities:"tenant", pet:"not-allowed", income:"Full payment or bank guarantee", size:1000, school:800, bus:300, restaurant:500 },
    { title:"Penthouse in Kigali Heights", price:3500, images:["https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=1260","https://images.pexels.com/photos/2724749/pexels-photo-2724749.jpeg?auto=compress&cs=tinysrgb&w=1260","https://images.pexels.com/photos/1571453/pexels-photo-1571453.jpeg?auto=compress&cs=tinysrgb&w=1260"], address:"KG 7 Ave, Kigali Heights, Kigali", city:"Kigali", bedroom:3, bathroom:3, latitude:-1.9500, longitude:30.0930, type:"rent", property:"apartment", agentIdx:0, desc:"Top-floor penthouse with panoramic views of Kigali. Floor-to-ceiling windows, rooftop terrace, gym access and concierge service included.", utilities:"owner", pet:"not-allowed", income:"4x monthly rent", size:220, school:600, bus:200, restaurant:150 },
    { title:"Townhouse in Gacuriro", price:280000, images:["https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1260","https://images.pexels.com/photos/1643384/pexels-photo-1643384.jpeg?auto=compress&cs=tinysrgb&w=1260"], address:"Gacuriro Estate, Gasabo, Kigali", city:"Kigali", bedroom:3, bathroom:2, latitude:-1.9200, longitude:30.1050, type:"buy", property:"house", agentIdx:2, desc:"Modern 3-bedroom townhouse in the popular Gacuriro Estate. Gated community with shared garden, children playground and 24/7 security.", utilities:"shared", pet:"allowed", income:"Mortgage or full payment", size:180, school:700, bus:400, restaurant:600 },
    // ── MUSANZE (Northern Province) ──────────────────────────────────────
    { title:"Mountain View Lodge in Musanze", price:1800, images:["https://images.pexels.com/photos/2506988/pexels-photo-2506988.jpeg?auto=compress&cs=tinysrgb&w=1260","https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg?auto=compress&cs=tinysrgb&w=1260","https://images.pexels.com/photos/1134176/pexels-photo-1134176.jpeg?auto=compress&cs=tinysrgb&w=1260"], address:"Muhoza Sector, Musanze", city:"Musanze", bedroom:4, bathroom:3, latitude:-1.4990, longitude:29.6340, type:"rent", property:"house", agentIdx:3, desc:"Breathtaking lodge-style home at the foot of the Virunga volcanoes. Perfect for tourism business or private residence. Stunning views of Mt Karisimbi.", utilities:"tenant", pet:"allowed", income:"Proof of income required", size:320, school:1500, bus:600, restaurant:400 },
    { title:"Cosy Cottage near Gorilla Trekking", price:95000, images:["https://images.pexels.com/photos/1396132/pexels-photo-1396132.jpeg?auto=compress&cs=tinysrgb&w=1260","https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg?auto=compress&cs=tinysrgb&w=1260"], address:"Kinigi Sector, Musanze", city:"Musanze", bedroom:2, bathroom:1, latitude:-1.4700, longitude:29.5900, type:"buy", property:"house", agentIdx:0, desc:"Charming 2-bedroom cottage 2 km from Volcanoes National Park headquarters. Ideal for eco-tourism rental income. Surrounded by tea plantations.", utilities:"tenant", pet:"allowed", income:"Full payment or mortgage", size:120, school:2000, bus:800, restaurant:1200 },
    { title:"Apartment in Musanze Town Centre", price:450, images:["https://images.pexels.com/photos/1571471/pexels-photo-1571471.jpeg?auto=compress&cs=tinysrgb&w=1260","https://images.pexels.com/photos/1643389/pexels-photo-1643389.jpeg?auto=compress&cs=tinysrgb&w=1260"], address:"Muhoza, Musanze Town", city:"Musanze", bedroom:2, bathroom:1, latitude:-1.5010, longitude:29.6350, type:"rent", property:"apartment", agentIdx:1, desc:"Clean and affordable 2-bedroom apartment in Musanze town centre. Close to market, hospital and transport links to Kigali.", utilities:"owner", pet:"not-allowed", income:"2x monthly rent", size:80, school:500, bus:100, restaurant:200 },
    // ── RUBAVU / GISENYI (Western Province) ─────────────────────────────
    { title:"Lakefront Villa on Lake Kivu", price:4200, images:["https://images.pexels.com/photos/2373201/pexels-photo-2373201.jpeg?auto=compress&cs=tinysrgb&w=1260","https://images.pexels.com/photos/261102/pexels-photo-261102.jpeg?auto=compress&cs=tinysrgb&w=1260","https://images.pexels.com/photos/2119714/pexels-photo-2119714.jpeg?auto=compress&cs=tinysrgb&w=1260"], address:"Rubavu Beach Road, Gisenyi", city:"Rubavu", bedroom:5, bathroom:4, latitude:-1.6980, longitude:29.2560, type:"rent", property:"house", agentIdx:2, desc:"Exclusive lakefront villa with private beach access on Lake Kivu. Infinity pool, boat dock and stunning sunset views. Perfect for luxury holiday rental.", utilities:"owner", pet:"allowed", income:"4x monthly rent", size:500, school:2000, bus:500, restaurant:300 },
    { title:"Beach Apartment in Gisenyi", price:800, images:["https://images.pexels.com/photos/2029722/pexels-photo-2029722.jpeg?auto=compress&cs=tinysrgb&w=1260","https://images.pexels.com/photos/1571463/pexels-photo-1571463.jpeg?auto=compress&cs=tinysrgb&w=1260"], address:"Rubavu Town, Gisenyi", city:"Rubavu", bedroom:2, bathroom:2, latitude:-1.7020, longitude:29.2580, type:"rent", property:"apartment", agentIdx:3, desc:"Modern 2-bedroom apartment 200m from Lake Kivu beach. Furnished with lake views from the balcony. Walking distance to restaurants and nightlife.", utilities:"owner", pet:"not-allowed", income:"2x monthly rent", size:95, school:800, bus:200, restaurant:100 },
    { title:"Land Plot with Lake View in Rubavu", price:120000, images:["https://images.pexels.com/photos/440731/pexels-photo-440731.jpeg?auto=compress&cs=tinysrgb&w=1260","https://images.pexels.com/photos/1029599/pexels-photo-1029599.jpeg?auto=compress&cs=tinysrgb&w=1260"], address:"Nyamyumba Sector, Rubavu", city:"Rubavu", bedroom:0, bathroom:0, latitude:-1.7200, longitude:29.2400, type:"buy", property:"land", agentIdx:0, desc:"600 sqm residential plot with panoramic Lake Kivu views. Ideal for building a holiday home or guesthouse. Title deed ready.", utilities:"tenant", pet:"not-allowed", income:"Full payment", size:600, school:3000, bus:1000, restaurant:1500 },
    // ── HUYE / BUTARE (Southern Province) ───────────────────────────────
    { title:"University Area House in Huye", price:600, images:["https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=1260","https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1260"], address:"Near UR Campus, Huye", city:"Huye", bedroom:3, bathroom:2, latitude:-2.5960, longitude:29.7390, type:"rent", property:"house", agentIdx:1, desc:"Spacious 3-bedroom house ideal for university staff or students. 5 minutes walk to University of Rwanda main campus. Quiet and secure neighbourhood.", utilities:"tenant", pet:"allowed", income:"2x monthly rent", size:160, school:300, bus:200, restaurant:400 },
    { title:"Modern Condo in Butare Town", price:220000, images:["https://images.pexels.com/photos/1571468/pexels-photo-1571468.jpeg?auto=compress&cs=tinysrgb&w=1260","https://images.pexels.com/photos/2029694/pexels-photo-2029694.jpeg?auto=compress&cs=tinysrgb&w=1260"], address:"Ngoma Sector, Huye", city:"Huye", bedroom:2, bathroom:2, latitude:-2.5980, longitude:29.7410, type:"buy", property:"condo", agentIdx:2, desc:"Brand new 2-bedroom condo in the cultural capital of Rwanda. Close to the National Museum, restaurants and the vibrant university town atmosphere.", utilities:"shared", pet:"not-allowed", income:"Mortgage or full payment", size:100, school:600, bus:300, restaurant:200 },
    { title:"Affordable Home in Huye Suburbs", price:85000, images:["https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1260","https://images.pexels.com/photos/1029599/pexels-photo-1029599.jpeg?auto=compress&cs=tinysrgb&w=1260"], address:"Tumba Sector, Huye", city:"Huye", bedroom:3, bathroom:1, latitude:-2.6100, longitude:29.7300, type:"buy", property:"house", agentIdx:3, desc:"Affordable 3-bedroom family home in a peaceful suburb of Huye. Large compound with fruit trees. Easy access to main road to Kigali.", utilities:"tenant", pet:"allowed", income:"Full payment or mortgage", size:200, school:1500, bus:700, restaurant:1000 },
    // ── MUHANGA / GITARAMA (Southern Province) ───────────────────────────
    { title:"Family Home in Muhanga", price:500, images:["https://images.pexels.com/photos/1396132/pexels-photo-1396132.jpeg?auto=compress&cs=tinysrgb&w=1260","https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1260"], address:"Shyogwe Sector, Muhanga", city:"Muhanga", bedroom:3, bathroom:2, latitude:-2.0830, longitude:29.7540, type:"rent", property:"house", agentIdx:0, desc:"Comfortable 3-bedroom home in Muhanga, halfway between Kigali and Huye on the main highway. Large garden, borehole water and solar power.", utilities:"tenant", pet:"allowed", income:"2x monthly rent", size:180, school:900, bus:300, restaurant:500 },
    { title:"Plot for Sale in Gitarama Centre", price:75000, images:["https://images.pexels.com/photos/440731/pexels-photo-440731.jpeg?auto=compress&cs=tinysrgb&w=1260","https://images.pexels.com/photos/280229/pexels-photo-280229.jpeg?auto=compress&cs=tinysrgb&w=1260"], address:"Muhanga Town Centre, Gitarama", city:"Muhanga", bedroom:0, bathroom:0, latitude:-2.0850, longitude:29.7560, type:"buy", property:"land", agentIdx:1, desc:"400 sqm commercial plot right in Gitarama town centre. High foot traffic area, suitable for shop, office or residential building. Title deed available.", utilities:"tenant", pet:"not-allowed", income:"Full payment", size:400, school:500, bus:100, restaurant:200 },
    // ── NYAGATARE (Eastern Province) ─────────────────────────────────────
    { title:"Ranch House in Nyagatare", price:700, images:["https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg?auto=compress&cs=tinysrgb&w=1260","https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=1260"], address:"Nyagatare Town, Eastern Province", city:"Nyagatare", bedroom:4, bathroom:2, latitude:-1.2960, longitude:30.3280, type:"rent", property:"house", agentIdx:2, desc:"Spacious ranch-style house in Rwandas cattle country. Large compound with garage and staff quarters. Ideal for agribusiness professionals.", utilities:"tenant", pet:"allowed", income:"2x monthly rent", size:280, school:1200, bus:400, restaurant:600 },
    { title:"Affordable Apartment in Nyagatare", price:350, images:["https://images.pexels.com/photos/1571471/pexels-photo-1571471.jpeg?auto=compress&cs=tinysrgb&w=1260","https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=1260"], address:"Karama Sector, Nyagatare", city:"Nyagatare", bedroom:2, bathroom:1, latitude:-1.2980, longitude:30.3300, type:"rent", property:"apartment", agentIdx:3, desc:"Clean 2-bedroom apartment in Nyagatare town. Close to the main market, district hospital and bus park. Reliable water and electricity supply.", utilities:"owner", pet:"not-allowed", income:"2x monthly rent", size:75, school:600, bus:150, restaurant:300 },
    { title:"Agricultural Land in Nyagatare", price:95000, images:["https://images.pexels.com/photos/440731/pexels-photo-440731.jpeg?auto=compress&cs=tinysrgb&w=1260","https://images.pexels.com/photos/1029599/pexels-photo-1029599.jpeg?auto=compress&cs=tinysrgb&w=1260"], address:"Karangazi Sector, Nyagatare", city:"Nyagatare", bedroom:0, bathroom:0, latitude:-1.2500, longitude:30.4000, type:"buy", property:"land", agentIdx:0, desc:"5 hectares of fertile agricultural land in Karangazi, ideal for maize, soya or cattle farming. Irrigation canal nearby. Title deed available.", utilities:"tenant", pet:"not-allowed", income:"Full payment", size:50000, school:5000, bus:2000, restaurant:3000 },
    // ── RWAMAGANA (Eastern Province) ─────────────────────────────────────
    { title:"Modern Home in Rwamagana", price:550, images:["https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=1260","https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1260"], address:"Kigabiro Sector, Rwamagana", city:"Rwamagana", bedroom:3, bathroom:2, latitude:-1.9490, longitude:30.4350, type:"rent", property:"house", agentIdx:1, desc:"Well-maintained 3-bedroom home in Rwamagana, the gateway to Eastern Province. 45 minutes from Kigali on tarmac road. Borehole water and solar.", utilities:"tenant", pet:"allowed", income:"2x monthly rent", size:170, school:800, bus:300, restaurant:500 },
    { title:"Condo for Sale in Rwamagana", price:160000, images:["https://images.pexels.com/photos/1571468/pexels-photo-1571468.jpeg?auto=compress&cs=tinysrgb&w=1260","https://images.pexels.com/photos/2029694/pexels-photo-2029694.jpeg?auto=compress&cs=tinysrgb&w=1260"], address:"Rwamagana Town Centre", city:"Rwamagana", bedroom:2, bathroom:2, latitude:-1.9510, longitude:30.4370, type:"buy", property:"condo", agentIdx:2, desc:"Brand new 2-bedroom condo in Rwamagana town. Modern kitchen, tiled floors and backup generator. Great investment property close to the new industrial zone.", utilities:"shared", pet:"not-allowed", income:"Mortgage or full payment", size:90, school:500, bus:200, restaurant:300 },
    // ── RUSIZI / CYANGUGU (Western Province) ─────────────────────────────
    { title:"Lakeside House in Rusizi", price:900, images:["https://images.pexels.com/photos/2373201/pexels-photo-2373201.jpeg?auto=compress&cs=tinysrgb&w=1260","https://images.pexels.com/photos/1396132/pexali-photo-1396132.jpeg?auto=compress&cs=tinysrgb&w=1260"], address:"Cyangugu Town, Rusizi", city:"Rusizi", bedroom:3, bathroom:2, latitude:-2.4840, longitude:28.9070, type:"rent", property:"house", agentIdx:3, desc:"Beautiful 3-bedroom house on the shores of Lake Kivu in Cyangugu. Stunning views of the DRC across the lake. Peaceful neighbourhood with good security.", utilities:"tenant", pet:"allowed", income:"2x monthly rent", size:200, school:1000, bus:400, restaurant:600 },
    { title:"Affordable Plot in Rusizi", price:45000, images:["https://images.pexels.com/photos/440731/pexels-photo-440731.jpeg?auto=compress&cs=tinysrgb&w=1260","https://images.pexels.com/photos/280229/pexels-photo-280229.jpeg?auto=compress&cs=tinysrgb&w=1260"], address:"Kamembe Sector, Rusizi", city:"Rusizi", bedroom:0, bathroom:0, latitude:-2.4700, longitude:28.9100, type:"buy", property:"land", agentIdx:0, desc:"300 sqm residential plot in Kamembe, Rusizi. Flat terrain, easy to build. Close to Kamembe Airport and the DRC border crossing.", utilities:"tenant", pet:"not-allowed", income:"Full payment", size:300, school:1200, bus:500, restaurant:800 }
  ];

  const agents = [a1, a2, a3, a4];

  for (const p of posts) {
    const { agentIdx, desc, utilities, pet, income, size, school, bus, restaurant, ...postData } = p;
    await prisma.post.create({
      data: {
        ...postData,
        userId: agents[agentIdx].id,
        postDetail: {
          create: { desc, utilities, pet, income, size, school, bus, restaurant },
        },
      },
    });
    console.log("  Created:", p.title);
  }

  console.log(`\nDone! Seeded ${posts.length} posts across Rwanda.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
